### ISSUE TITLE
我想问一下，为啥加载服务端证书不需要密码？

### ISSUE THREAD

**Issue by szmichaelyb** [codeliu6572/New_AFNetworking_For_HTTPS#2]
我想问一下，为啥加载服务端证书不需要密码？如果是单向验证，没有密码，拆包岂不是很容易拿到这个证书？

**Comment by codeliu6572** [comment]
单向验证需要一个cer，而你在导出cer的时候系统不会提醒你设置密码，所以在使用https时SSL特指的是双向验证，单向验证和跳过证书验证的意义，个人认为只是非明文传输，抓包拿不到数据，而即使是被拿到证书，抓不到包，也是拿不到你们数据的吧？
